### ISSUE TITLE
Import packages and modules from the top level

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/mirrors-countme#33]
# Story

As a developer of mirrors-countme,
I want its modules to import other modules and packages at the top,
so I can easily see what their dependencies are.

# Acceptance Criteria

- [x] Other modules and packages are imported at the top level of each module.

# Background

Currently some modules are imported from within functions instead of at the top level of modules:

```
(mirrors-countme) nils@makake:~/src/fedora-infra/mirrors-countme (main)> git grep '^\s\+.*import' -- \*.py
mirrors_countme/__init__.py:        import json
mirrors_countme/__init__.py:        import csv
mirrors_countme/__init__.py:        import sqlite3
mirrors_countme/__init__.py:        import csv
mirrors_countme/__init__.py:        import json
mirrors_countme/__init__.py:        import sqlite3
mirrors_countme/parse.py:        import subprocess
mirrors_countme/progress.py:        import lzma
mirrors_countme/progress.py:        import gzip
mirrors_countme/progress.py:    import subprocess
mirrors_countme/progress.py:    import subprocess
(mirrors-countme) nils@makake:~/src/fedora-infra/mirrors-countme (main)>
```

I don’t know why it was done this way, usually this is done to have optional functionality which has 3rd party dependencies which you don’t want your users to be forced to install always, but these are all modules that come with the Python stdlib.

**Comment by LenkaSeg** [comment]
Related PR #42
