### ISSUE TITLE
Docs, docs, docs

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/mirrors-countme#84]
# Story

As an operator of DNF mirrors-countme,
I would like that its SOP reflects the changes in the initiative,
so I’m not mislead.

# Acceptance Criteria

The [DNF Counting SOP](https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/dnf-counting/) is…

- [x] updated,
- [x] added to,
- [x] cleaned out

…so it matches up with reality (so far as we know it 😜), in particular the changes that were implemented during the initiative.

**Comment by nphilipp** [comment]
Submitted a PR in the Fedora docs repo: https://pagure.io/infra-docs-fpo/pull-request/216

**Comment by LenkaSeg** [comment]
PR in infra-docs-fpo is merged, all checkboxes checked, closing this issue.
